export const dashboardStats = {
  totalUsers: 14582,
  activeUsers: 11204,
  inactiveUsers: 3378,
  newMatches: 842,
  averageSessionTime: '28.4',
  userGrowthRate: 15.2,
  engagementRate: 72.5,
  revenue: 185400,
  conversionRate: 4.8,
}

export const users = [
  {
    id: 'USR-001',
    name: 'Nguyễn Diệu Linh',
    email: 'dieulinh.n@gmail.com',
    status: 'active',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    bio: 'Tìm kiếm một linh hồn đồng điệu, yêu âm nhạc cổ điển và những buổi chiều đọc sách.',
    interests: ['Âm nhạc', 'Sách', 'Du lịch', 'Nghệ thuật'],
    personalityTags: ['Hướng nội', 'Nhạy cảm', 'Sâu sắc', 'Chân thành'],
    age: 24,
    gender: 'Nữ',
    location: 'Hà Nội, Việt Nam',
    matches: 156,
    activityScore: 92,
    joinDate: '15/01/2024',
    lastActive: '31/03/2026 14:20',
  },
  {
    id: 'USR-002',
    name: 'Trần Minh Quân',
    email: 'minhquan.t@outlook.com',
    status: 'active',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    bio: 'Đam mê công nghệ và leo núi. Thích những trải nghiệm mới lạ và đầy thử thách.',
    interests: ['Công nghệ', 'Leo núi', 'Nấu ăn', 'Gym'],
    personalityTags: ['Năng động', 'Quyết đoán', 'Hài hước', 'Tự tin'],
    age: 28,
    gender: 'Nam',
    location: 'TP. Hồ Chí Minh, Việt Nam',
    matches: 84,
    activityScore: 78,
    joinDate: '20/02/2024',
    lastActive: '31/03/2026 16:45',
  },
  {
    id: 'USR-003',
    name: 'Lê Thu Thảo',
    email: 'thuthao.le@yahoo.com',
    status: 'flagged',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
    bio: 'Nhiếp ảnh gia nghiệp dư. Yêu mèo và những chuyến đi phượt ngẫu hứng.',
    interests: ['Nhiếp ảnh', 'Thú cưng', 'Phượt', 'Điện ảnh'],
    personalityTags: ['Sáng tạo', 'Tự do', 'Vui vẻ', 'Phóng khoáng'],
    age: 25,
    gender: 'Nữ',
    location: 'Đà Nẵng, Việt Nam',
    matches: 120,
    activityScore: 85,
    joinDate: '10/12/2023',
    lastActive: '28/03/2026 09:12',
  },
  {
    id: 'USR-004',
    name: 'Phạm Hoàng Nam',
    email: 'hoangnam.p@gmail.com',
    status: 'active',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
    bio: 'Thích rượu vang và các bảo tàng nghệ thuật. Đang tìm một người cùng gu thưởng thức.',
    interests: ['Rượu vang', 'Bảo tàng', 'Lịch sử', 'Giao lưu'],
    personalityTags: ['Lịch thiệp', 'Thông minh', 'Trầm tính', 'Ổn định'],
    age: 32,
    gender: 'Nam',
    location: 'Hà Nội, Việt Nam',
    matches: 42,
    activityScore: 65,
    joinDate: '05/03/2024',
    lastActive: '31/03/2026 12:30',
  },
  {
    id: 'USR-005',
    name: 'Hoàng Kim Ngân',
    email: 'kimngan.h@gmail.com',
    status: 'banned',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop',
    bio: 'Gamer chính hiệu. Streamer bán thời gian. Thích anime và coding.',
    interests: ['Gaming', 'Anime', 'Coding', 'Công nghệ'],
    personalityTags: ['Nhạy bén', 'Thẳng thắn', 'Độc lập', 'Nhiệt huyết'],
    age: 22,
    gender: 'Nữ',
    location: 'Cần Thơ, Việt Nam',
    matches: 215,
    activityScore: 98,
    joinDate: '28/01/2024',
    lastActive: '25/03/2026 23:55',
  },
]

export const auditLogs = [
  {
    id: 'LOG-001',
    adminName: 'Admin Toàn Cầu',
    action: 'Chặn người dùng',
    target: 'Hoàng Kim Ngân (USR-005)',
    timestamp: '31/03/2026 15:30',
  },
  {
    id: 'LOG-002',
    adminName: 'Admin Toàn Cầu',
    action: 'Sửa câu hỏi AI',
    target: 'Câu hỏi ID #102',
    timestamp: '31/03/2026 14:15',
  },
  {
    id: 'LOG-003',
    adminName: 'Admin Toàn Cầu',
    action: 'Tạo thử thách mới',
    target: 'Thử thách: Bắt đầu trò chuyện',
    timestamp: '30/03/2026 10:00',
  },
]

export const questions = [
  {
    id: '1',
    text: 'Buổi hẹn hò lý tưởng của bạn sẽ như thế nào?',
    category: 'Hẹn hò',
    type: 'Câu hỏi mở',
    goal: 'Lối sống & Sở thích',
    responses: 12450,
    avgTime: 45,
    completionRate: 85,
    difficulty: 'Easy',
    status: 'active',
    weights: { 'Hướng ngoại': 0.8, 'Sáng tạo': 0.5 },
  },
  {
    id: '2',
    text: '3 mục tiêu lớn nhất trong cuộc đời bạn là gì?',
    category: 'Cá nhân',
    type: 'Câu hỏi mở',
    goal: 'Tầm nhìn & Giá trị',
    responses: 8900,
    avgTime: 120,
    completionRate: 72,
    difficulty: 'Hard',
    status: 'active',
    weights: { 'Quyết đoán': 0.9, 'Ổn định': 0.7 },
  },
  {
    id: '3',
    text: 'Nếu có một ngày nghỉ không giới hạn ngân sách, bạn sẽ đi đâu?',
    category: 'Lối sống',
    type: 'Trắc nghiệm',
    goal: 'Sở thích & Ngân sách',
    responses: 15600,
    avgTime: 30,
    completionRate: 98,
    difficulty: 'Easy',
    status: 'active',
    weights: { 'Tự do': 1.0, 'Khám phá': 0.8 },
  },
  {
    id: '4',
    text: 'Bạn xử lý xung đột trong mối quan hệ như thế nào?',
    category: 'Mối quan hệ',
    type: 'Kịch bản',
    goal: 'Trí tuệ cảm xúc',
    responses: 5200,
    avgTime: 180,
    completionRate: 64,
    difficulty: 'Hard',
    status: 'inactive',
    weights: { 'Nhạy cảm': 0.6, 'Chân thành': 0.9 },
  },
]

export const analyticsData = [
  { date: 'Thứ 2', users: 2400, matches: 240, messages: 2210, aiMatches: 180 },
  { date: 'Thứ 3', users: 3398, matches: 221, messages: 2290, aiMatches: 165 },
  { date: 'Thứ 4', users: 4800, matches: 229, messages: 2000, aiMatches: 190 },
  { date: 'Thứ 5', users: 3908, matches: 200, messages: 2181, aiMatches: 140 },
  { date: 'Thứ 6', users: 4800, matches: 478, messages: 2500, aiMatches: 350 },
  { date: 'Thứ 7', users: 6500, matches: 842, messages: 5200, aiMatches: 580 },
  { date: 'Chủ nhật', users: 5490, matches: 567, messages: 3100, aiMatches: 420 },
]

export const gamificationAchievements = [
  {
    id: '1',
    name: 'Ghép đôi đầu tiên',
    description: 'Nhận được lượt ghép đôi đầu tiên của bạn',
    icon: '💕',
    unlocked: 8450,
    rarity: 'Phổ biến',
    xpReward: 100,
    status: 'active',
  },
  {
    id: '2',
    name: 'Kẻ chinh phục',
    description: 'Nhận 10 lượt ghép đôi trong vòng một tuần',
    icon: '🔥',
    unlocked: 2100,
    rarity: 'Hiếm',
    xpReward: 500,
    status: 'active',
  },
  {
    id: '3',
    name: 'Người kể chuyện',
    description: 'Gửi 100 tin nhắn đầu tiên',
    icon: '💬',
    unlocked: 4567,
    rarity: 'Phổ biến',
    xpReward: 200,
    status: 'active',
  },
  {
    id: '4',
    name: 'Trái tim rực cháy',
    description: 'Duy trì chuỗi ghép đôi trong 30 ngày',
    icon: '🌹',
    unlocked: 540,
    rarity: 'Sử thi',
    xpReward: 2000,
    status: 'active',
  },
]

export const chatMetrics = [
  { metric: 'Tổng tin nhắn', value: '2.45M', change: 12.5 },
  { metric: 'Độ dài tin nhắn TB', value: '42 ký tự', change: -2.3 },
  { metric: 'Thời gian phản hồi', value: '8.2 phút', change: -4.1 },
  { metric: 'Tỷ lệ chuyển đổi Chat', value: '18.5%', change: 3.2 },
]
